name: Web TV CANAL 040

on:
  schedule:
    - cron: '0 10 * * *' # 07:00 BRT
    - cron: '0 15 * * *' # 12:00 BRT
    - cron: '0 20 * * *' # 17:00 BRT
    - cron: '0 1 * * *'  # 22:00 BRT
  workflow_dispatch:     # Permite ligar manualmente para testes

jobs:
  transmitir:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar arquivos do projeto
      uses: actions/checkout@v4

    - name: Instalar o FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Transmitir Sinal de TV Direto
      run: |
        # Inicia a conversao direta do video de teste de forma infinita
        mkdir -p hls
        echo "Iniciando a transmissão direta no site..."
        
        # Link de teste oficial estável integrado direto no motor do servidor
        ffmpeg -re -stream_loop -1 -i "https://googleapis.com" -c:v libx264 -preset veryfast -b:v 1500k -maxrate 1500k -bufsize 2000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 -f hls -hls_time 4 -hls_list_size 5 -hls_flags delete_segments hls/sinal.m3u8
