name: Web TV CANAL 040

on:
  schedule:
    - cron: '0 10 * * *' # 07:00 BRT
    - cron: '0 15 * * *' # 12:00 BRT
    - cron: '0 20 * * *' # 17:00 BRT
    - cron: '0 1 * * *'  # 22:00 BRT
  workflow_dispatch:

jobs:
  transmitir:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar arquivos do projeto
      uses: actions/checkout@v3

    - name: Instalar o FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Rodar Playlist Inteligente por Horário
      env:
        CHAVE_STREAM: ${{ secrets.CHAVE_STREAM }}
      run: |
        HORA_AGORA=$(date -d '3 hours ago' +%H)
        echo "A hora atual no Brasil é: $HORA_AGORA:00"

        if [ "$HORA_AGORA" -ge 7 ] && [ "$HORA_AGORA" -lt 12 ]; then
          PASTA_ATUAL="manha"
        elif [ "$HORA_AGORA" -ge 12 ] && [ "$HORA_AGORA" -lt 17 ]; then
          PASTA_ATUAL="tarde"
        elif [ "$HORA_AGORA" -ge 17 ] && [ "$HORA_AGORA" -lt 22 ]; then
          PASTA_ATUAL="noite"
        elif [ "$HORA_AGORA" -ge 22 ] && [ "$HORA_AGORA" -lt 24 ]; then
          PASTA_ATUAL="final"
        else
          echo "Madrugada. Desligado."
          exit 0
        fi

        # Lê a lista de vídeos da pasta do bloco atual
        if [ -f "video_files/${PASTA_ATUAL}/playlist.txt" ]; then
          while true; do
            while read -r link_video; do
              if [ ! -z "$link_video" ]; then
                echo "Transmitindo: $link_video"
                ffmpeg -re -i "$link_video" -c:v libx264 -preset veryfast -b:v 2000k -maxrate 2000k -bufsize 2500k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 -f flv "rtmp://localhost/live/$CHAVE_STREAM"
              fi
            done < "video_files/${PASTA_ATUAL}/playlist.txt"
          done
        else
          echo "Crie o arquivo playlist.txt em: video_files/${PASTA_ATUAL}/"
          exit 1
        fi
